name: Verify and Upload nyx_client and nyx_extras to TEST PyPI
on:
  workflow_dispatch:
jobs:
  verify_and_upload:
    strategy:
      fail-fast: false
      matrix:
        project: [nyx_client, nyx_extras]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies for nyx_client
        if: matrix.project == 'nyx_client'
        run: poetry install --with dev --no-interaction
        env:
          POETRY_INSTALLER_PARALLEL: 0
      - name: Install dependencies for nyx_extras
        if: matrix.project == 'nyx_extras'
        run: poetry install --with dev --extras "langchain-openai langchain-cohere" --no-interaction
        env:
          POETRY_INSTALLER_PARALLEL: 0
      - run: make lint
      - run: make tests
      - run: make build
      - name: Verify wheel installation
        run: |
          pip install dist/${{ matrix.project }}*.whl
          python -c "from ${{ matrix.project }} import *"
          pip uninstall -y ${{ matrix.project }}
      - name: Verify tar.gz installation
        run: |
          pip install dist/${{ matrix.project }}*.tar.gz
          python -c "from ${{ matrix.project }} import *"
          pip uninstall -y ${{ matrix.project }}
      - name: Publish package to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD2024 }}
          packages-dir: ${{ matrix.project }}/dist/
          verify-metadata: true
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: false

  # Add a check job to ensure proper workflow status reporting
  completion_check:
    needs: verify_and_upload
    runs-on: ubuntu-latest
    steps:
      - run: echo "All packages verified and uploaded successfully!"
