on:
  workflow_dispatch:

jobs:
  verify_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.14

      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: poetry install --with dev --extras "langchain-openai langchain-cohere" --no-interaction

      - run: make lint

      - run: make tests

      - run: make build

      - run: |
          pip install dist/nyx_client*.whl
          python -c "from nyx_client import NyxClient, Data"
          pip uninstall -y nyx_client

      - run: |
          pip install dist/nyx_client*.tar.gz
          python -c "from nyx_client import NyxClient, Data"
          pip uninstall -y nyx_client

      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD2024 }}
          packages-dir: ./dist/
          verify-metadata: true
          verbose: true
          skip-existing: false
