permissions:
  id-token: write

name: Verify and Upload nyx_client and nyx_extras to PyPI
on:
  workflow_dispatch:
jobs:
  verify_and_upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nyx_client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies for nyx_client
        run: poetry install --with dev --no-interaction
        env:
          POETRY_INSTALLER_PARALLEL: 0
      - run: make lint
      - run: make tests
      - run: make build
      - name: Verify wheel installation
        run: |
          pip install dist/nyx_client*.whl
          python -c "from nyx_client import *"
          pip uninstall -y nyx_client
      - name: Verify tar.gz installation
        run: |
          pip install dist/nyx_client*.tar.gz
          python -c "from nyx_client import NyxClient, Data"
          pip uninstall -y nyx_client
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          packages-dir: nyx_client/dist/
          verify-metadata: true
          verbose: true
          skip-existing: false
  
  verify_and_upload_extras:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nyx_extras
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies for nyx_extras
        run: poetry install --with dev --extras "langchain-openai langchain-cohere" --no-interaction
        env:
          POETRY_INSTALLER_PARALLEL: 0
      - run: make lint
      - run: make tests
      - run: make build
      - name: Verify wheel installation
        run: |
          pip install dist/nyx_extras*.whl
          pip install langchain langchain-openai langchain-community
          python -c "from nyx_extras import *"
          pip uninstall -y nyx_extras
      - name: Verify tar.gz installation
        run: |
          pip install dist/nyx_extras*.tar.gz
          python -c "from nyx_extras import *"
          pip uninstall -y nyx_extras
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD2024 }}
          packages-dir: nyx_extras/dist/
          verify-metadata: true
          verbose: true
          skip-existing: false

  completion_check:
    needs: verify_and_upload
    runs-on: ubuntu-latest
    steps:
      - run: echo "All packages verified and uploaded successfully to PyPI!"
